version: '3.9'
services:
  postgres:
    container_name: polarDb
    restart: always
    build:
      context: backend/sql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: polar
    ports:
      - '5434:5432'
