export const cvprocesses = [
    {id: 1, loading: 0, status: 'pending'},
    {id: 2, loading: 0, status: 'pending'},
    {id: 3, loading: 0, status: 'pending'},
    {id: 4, loading: 0, status: 'pending'},
    {id: 5, loading: 0, status: 'pending'},
    {id: 6, loading: 0, status: 'pending'},
    {id: 7, loading: 0, status: 'pending'},
    {id: 8, loading: 0, status: 'pending'},
    {id: 9, loading: 0, status: 'pending'},
    {id: 10, loading: 0, status: 'pending'},
    {id: 11, loading: 0, status: 'pending'},
    {id: 12, loading: 0, status: 'pending'},
    {id: 13, loading: 0, status: 'pending'},
    {id: 14, loading: 0, status: 'pending'},
    {id: 15, loading: 0, status: 'pending'},
    {id: 16, loading: 0, status: 'pending'},
    {id: 17, loading: 0, status: 'pending'},
    {id: 18, loading: 0, status: 'pending'},
    {id: 19, loading: 0, status: 'pending'},
];
